// <auto-generated />
namespace SchedulEasy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class h1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(h1));
        
        string IMigrationMetadata.Id
        {
            get { return "201808202054421_h1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
